/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package galacticaia;

import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLJPanel;
import com.jogamp.opengl.util.FPSAnimator;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Guilherme
 */
public class Principal extends javax.swing.JFrame {

    private Integer[][] campo;
    private IniciarCampo iniciarCampo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        final GLProfile profile = GLProfile.get(GLProfile.GL2);
        GLCapabilities capabilities = new GLCapabilities(profile);

        gLJPanel1.setRequestedGLCapabilities(capabilities);
        painelDesenho.add(gLJPanel1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        painelTopo = new javax.swing.JPanel();
        btArquivo = new javax.swing.JButton();
        editFile = new javax.swing.JTextField();
        btProcesso = new javax.swing.JButton();
        painelDesenho = new javax.swing.JPanel();
        gLJPanel1 = new com.jogamp.opengl.awt.GLJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btArquivo.setText("Abrir");
        btArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArquivoActionPerformed(evt);
            }
        });

        editFile.setEditable(false);

        btProcesso.setText("Processar IA");
        btProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTopoLayout = new javax.swing.GroupLayout(painelTopo);
        painelTopo.setLayout(painelTopoLayout);
        painelTopoLayout.setHorizontalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editFile, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btProcesso)
                .addGap(46, 46, 46))
        );
        painelTopoLayout.setVerticalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArquivo)
                    .addComponent(editFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProcesso)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gLJPanel1Layout = new javax.swing.GroupLayout(gLJPanel1);
        gLJPanel1.setLayout(gLJPanel1Layout);
        gLJPanel1Layout.setHorizontalGroup(
            gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gLJPanel1Layout.setVerticalGroup(
            gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gLJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gLJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(painelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArquivoActionPerformed

        jFileChooser1.showOpenDialog(null);
        File f = jFileChooser1.getSelectedFile();
        try {
            editFile.setText(f.getCanonicalPath());
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        iniciarCampo = new IniciarCampo(f);
        this.campo = iniciarCampo.getCampo();
        GalacticaEventGLE eventoGLE = new GalacticaEventGLE(iniciarCampo.getCampo());
        gLJPanel1.addGLEventListener(eventoGLE);

        final FPSAnimator animator = new FPSAnimator(gLJPanel1, 300, true);
        animator.start();
    }//GEN-LAST:event_btArquivoActionPerformed

    private void btProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcessoActionPerformed
        // TODO add your handling code here:
        int linha = this.campo.length;
        int coluna = this.campo[0].length;
        Coordenada position = iniciarCampo.getCoorIni();

        //ordenar a lista de boss mais proximo do ponto inicial (nao funciona)
        /* Collections.sort(iniciarCampo.getCoorBoss(), new Comparator<Coordenada>(){
            @Override
            public int compare(Coordenada p1, Coordenada p2) {
                Integer linha = iniciarCampo.getCoorIni().getLinha() - p1.getLinha();
                Integer coluna = iniciarCampo.getCoorIni().getColuna() - p1.getColuna();
                Integer distancia1 = Math.abs(linha) + Math.abs(coluna);
                
                Integer linha2 = iniciarCampo.getCoorIni().getLinha() - p2.getLinha();
                Integer coluna2 = iniciarCampo.getCoorIni().getColuna() - p2.getColuna();
                Integer distancia2 = Math.abs(linha2) + Math.abs(coluna2);
                
                return distancia1 < distancia2 ? -1 : 1;
            }
            
        });*/
        for (Coordenada boss : iniciarCampo.getCoorBoss()) {

            position = moverBoss(position, boss);

        }


    }//GEN-LAST:event_btProcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArquivo;
    private javax.swing.JButton btProcesso;
    private javax.swing.JTextField editFile;
    private com.jogamp.opengl.awt.GLJPanel gLJPanel1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelTopo;
    // End of variables declaration//GEN-END:variables

    public Integer getDistancia(Coordenada p1, Coordenada p2) {
        Integer linha = Math.abs(p1.getLinha() - p2.getLinha());
        Integer coluna = Math.abs(p1.getColuna() - p2.getColuna());

        return linha + coluna;
    }

    public Coordenada moverBoss(Coordenada position, Coordenada boss) {
        Coordenada result = null;
        
        if(campo[position.getLinha()][position.getColuna()] != 10)
            campo[position.getLinha()][position.getColuna()] = 10;
        try {
            System.out.println("Esperando");
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Coordenada pSuperior = new Coordenada(position.getLinha() - 1, position.getColuna());
        Coordenada pInferior = new Coordenada(position.getLinha() + 1, position.getColuna());
        Coordenada pDireita = new Coordenada(position.getLinha(), position.getColuna() + 1);
        Coordenada pEsquerda = new Coordenada(position.getLinha(), position.getColuna() - 1);
        
        if(Coordenada.isCoordenateEqual(boss, pSuperior)){
            result = pSuperior;
        }else if (Coordenada.isCoordenateEqual(boss, pInferior)){
            result = pInferior;
        }else if (Coordenada.isCoordenateEqual(boss, pDireita)){
            result = pDireita;
        }else if (Coordenada.isCoordenateEqual(boss, pEsquerda)){
            result = pEsquerda;
        }
        
        if(result == null){
            Integer somaCustoSuperior = this.getDistancia(pSuperior, boss) + campo[pSuperior.getLinha()][pSuperior.getColuna()];
            Integer somaCustoInferior = this.getDistancia(pInferior, boss) + campo[pInferior.getLinha()][pInferior.getColuna()];
            Integer somaCustoDireita = this.getDistancia(pDireita, boss) + campo[pDireita.getLinha()][pDireita.getColuna()];
            Integer somaCustoEsquerda = this.getDistancia(pEsquerda, boss) + campo[pEsquerda.getLinha()][pEsquerda.getColuna()];

            if (somaCustoSuperior < somaCustoInferior && somaCustoSuperior < somaCustoDireita && somaCustoSuperior < somaCustoEsquerda) {
                moverBoss(pSuperior, boss);
            } else if (somaCustoInferior < somaCustoDireita && somaCustoInferior < somaCustoEsquerda) {
                moverBoss(pInferior, boss);
            } else if (somaCustoDireita < somaCustoEsquerda) {
                moverBoss(pDireita, boss);
            } else {
                moverBoss(pEsquerda, boss);
            }
        }
        
        return result;
        
    }

}
